<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
    <Configurations>Debug;Release;Publish;test</Configurations>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PackageIcon>rocket128x128.ico</PackageIcon>
    <ApplicationIcon>rocket256x256.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.*" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="FileManager\game-credits.txt">
      <TargetPath>game-credits.txt</TargetPath> 
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory> 
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory> 
    </Content>
    <Content Include="rocket128x128.ico" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="FileManager\FileManager.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="rocket128x128.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="rocket256x256.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>


